# Generated by Django 3.1.2 on 2020-10-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainGastos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiles',
            name='fecha_de_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
