# Generated by Django 3.1.2 on 2020-10-24 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainGastos', '0002_auto_20201021_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='fk_id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainGastos.categorias'),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='fk_id_perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainGastos.perfiles'),
        ),
    ]
